### ISSUE TITLE
Difference between NONE and PERMANENT in a write change to parameter e.g. 1xxx

### ISSUE THREAD

**Issue by Jusufs** [OpenStuder/openstuder-client-python#2]
Hi.
Please explain me next behavior:
NONE = writes a parameter change e.g. 1xxx only to RAM
PERMANENT = writes a parameter change to FLASH
Is this dependent on state of 1550 (Flash on Yes/No) ?
How should this be coded in python sync/async routines ?
Thanks.

def test_encode_with_value_empty_flags(self):
        frame = _SIAbstractGatewayClient.encode_write_property_frame('demo.inv.3333', 42.24, SIWriteFlags.NONE)
        self.assertEqual('WRITE PROPERTY\nid:demo.inv.3333\nflags:\nvalue:42.24\n\n', frame)
 def test_encode_with_value_permanent_flag(self):
        frame = _SIAbstractGatewayClient.encode_write_property_frame('demo.inv.3333', 42.24, SIWriteFlags.PERMANENT)
        self.assertEqual('WRITE PROPERTY\nid:demo.inv.3333\nflags:Permanent\nvalue:42.24\n\n', frame)

**Comment by cm0x4D** [comment]
My understanding is that parameter 1550 is a global configuration for the XTender, where you can disable flash storage globally for the device. If you then write a parameter with the PERMANENT flag, it is not saved to flash and might return an error (I never did test that). I would keep that parameter at it's default value (Yes) and use the write flag to control that behaviour. 

If you pass nothing for the write flags parameter to the function, the device will save it to the flash by default.

**Comment by Jusufs** [comment]
Thanks Michael. May I call you by Whatsup or Viber. Is it possible to speak German ?
I would like to speak about write_property behavior with you.

Is this a valid contact ?
<html>
<body>


Role | Senior academic associate UAS
-- | --
Ingenieur HES
+41 58 606 87 26
michael.clausen@hevs.ch
https://www.linkedin.com/in/cm0x4d/
ENP.23.N306


</body>
</html>
I'm a retired automation technitian from Slovakia.
jozef.szabo@email.cz
+421 911 977333

Please delete infos, they should not be displayed here.

Role	
Senior academic associate UAS
Education	Ingenieur HES
Phone	
[+41 58 606 87 26](tel:+41 58 606 87 26)
Email	[michael.clausen@hevs.ch](mailto:michael.clausen@hevs.ch)
Linkedin	https://www.linkedin.com/in/cm0x4d/
Office	ENP.23.N306

**Comment by cm0x4D** [comment]
Hello Jusufs,

Please use GitHub issues only for reporting bugs or requests for improvements. Currently due to very limited resources, we can not provide support for the software.

The documentation for the synchronous client is [here](http://www.openstuder.io/#/clientlibs?id=writing-properties-write_property) and for the asynchronous client [here](http://www.openstuder.io/#/clientlibs?id=writing-properties-write_property-1). Additionally there are some examples [here (sync)](https://github.com/OpenStuder/openstuder-client-python/blob/main/examples/sync/write_property.py) and [here (async)](https://github.com/OpenStuder/openstuder-client-python/blob/main/examples/async/write_property.py).

Should the documentation for the `write_parameter()` function not be clear, let us know so we can improve the documentation.

**Comment by Jusufs** [comment]
Thanks
